package com.casaba.lab8.service;  // Note: Changed package to .service

import com.casaba.lab8.entity.Product;
import com.casaba.lab8.repository.ProductRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import javax.annotation.PostConstruct;  // <-- ADD THIS IMPORT
import java.util.List;
import java.util.Optional;

@Service
@Transactional
public class ProductService {

    @Autowired
    private ProductRepository productRepository;

    // Preload some initial data
    @PostConstruct
    public void init() {
        if (productRepository.count() == 0) {
            productRepository.save(new Product(null, "Laptop Pro", 59999.0, null, 10));
            productRepository.save(new Product(null, "Gaming Mouse", 1299.0, null, 50));
            productRepository.save(new Product(null, "Mechanical Keyboard", 4599.0, null, 30));
        }
    }

    public List<Product> getAllProducts() {
        return productRepository.findAll();
    }

    public Optional<Product> getProductById(Long id) {
        return productRepository.findById(id);
    }

    public Product createProduct(Product product) {
        // ID will be auto-generated by JPA
        return productRepository.save(product);
    }

    public Product updateProduct(Long id, Product updatedProduct) {
        return productRepository.findById(id)
                .map(existingProduct -> {
                    // Update only the fields that should change
                    existingProduct.setName(updatedProduct.getName());
                    existingProduct.setPrice(updatedProduct.getPrice());
                    existingProduct.setDescription(updatedProduct.getDescription());
                    existingProduct.setQuantity(updatedProduct.getQuantity());

                    return productRepository.save(existingProduct);
                })
                .orElse(null); // Returns null if product not found
    }

    public boolean deleteProduct(Long id) {
        if (productRepository.existsById(id)) {
            productRepository.deleteById(id);
            return true;
        }
        return false;
    }
}